2023-06-15 19:49:58,616 INFO    MainThread:53866 [wandb_setup.py:_flush():76] Current SDK version is 0.15.4
2023-06-15 19:49:58,617 INFO    MainThread:53866 [wandb_setup.py:_flush():76] Configure stats pid to 53866
2023-06-15 19:49:58,617 INFO    MainThread:53866 [wandb_setup.py:_flush():76] Loading settings from /Users/cglin/.config/wandb/settings
2023-06-15 19:49:58,617 INFO    MainThread:53866 [wandb_setup.py:_flush():76] Loading settings from /Users/cglin/Desktop/DL-project/wandb/settings
2023-06-15 19:49:58,617 INFO    MainThread:53866 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-06-15 19:49:58,617 INFO    MainThread:53866 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-06-15 19:49:58,617 INFO    MainThread:53866 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': '2.py', 'program': '/Users/cglin/Desktop/DL-project/2.py'}
2023-06-15 19:49:58,617 INFO    MainThread:53866 [wandb_init.py:_log_setup():507] Logging user logs to /Users/cglin/Desktop/DL-project/wandb/run-20230615_194958-x79pnrsx/logs/debug.log
2023-06-15 19:49:58,617 INFO    MainThread:53866 [wandb_init.py:_log_setup():508] Logging internal logs to /Users/cglin/Desktop/DL-project/wandb/run-20230615_194958-x79pnrsx/logs/debug-internal.log
2023-06-15 19:49:58,617 INFO    MainThread:53866 [wandb_init.py:init():547] calling init triggers
2023-06-15 19:49:58,617 INFO    MainThread:53866 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {'Learning Rate': 0.01, 'Batch size': 64, 'model': 'CNN'}
2023-06-15 19:49:58,617 INFO    MainThread:53866 [wandb_init.py:init():596] starting backend
2023-06-15 19:49:58,617 INFO    MainThread:53866 [wandb_init.py:init():600] setting up manager
2023-06-15 19:49:58,625 INFO    MainThread:53866 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2023-06-15 19:49:58,627 INFO    MainThread:53866 [wandb_init.py:init():606] backend started and connected
2023-06-15 19:49:58,631 INFO    MainThread:53866 [wandb_init.py:init():703] updated telemetry
2023-06-15 19:49:58,659 INFO    MainThread:53866 [wandb_init.py:init():736] communicating run to backend with 60.0 second timeout
2023-06-15 19:49:59,599 ERROR   MainThread:53866 [wandb_init.py:init():762] encountered error: The API key you provided is either invalid or missing.  If the `WANDB_API_KEY` environment variable is set, make sure it is correct. Otherwise, to resolve this issue, you may try running the 'wandb login --relogin' command. If you are using a local server, make sure that you're using the correct hostname. If you're not sure, you can try logging in again using the 'wandb login --relogin --host [hostname]' command.(Error 401: Unauthorized)
2023-06-15 19:50:00,038 ERROR   MainThread:53866 [wandb_init.py:init():1170] The API key you provided is either invalid or missing.  If the `WANDB_API_KEY` environment variable is set, make sure it is correct. Otherwise, to resolve this issue, you may try running the 'wandb login --relogin' command. If you are using a local server, make sure that you're using the correct hostname. If you're not sure, you can try logging in again using the 'wandb login --relogin --host [hostname]' command.(Error 401: Unauthorized)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1152, in init
    run = wi.init()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 768, in init
    raise error
wandb.errors.AuthenticationError: The API key you provided is either invalid or missing.  If the `WANDB_API_KEY` environment variable is set, make sure it is correct. Otherwise, to resolve this issue, you may try running the 'wandb login --relogin' command. If you are using a local server, make sure that you're using the correct hostname. If you're not sure, you can try logging in again using the 'wandb login --relogin --host [hostname]' command.(Error 401: Unauthorized)
2023-06-15 19:50:01,060 WARNING MsgRouterThr:53866 [router.py:message_loop():77] message_loop has been closed
